// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payments.proto

package payments

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OptionsRequest struct {
	Segment              string   `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	Msisdn               string   `protobuf:"bytes,2,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	BillType             string   `protobuf:"bytes,3,opt,name=billType,proto3" json:"billType,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionsRequest) Reset()         { *m = OptionsRequest{} }
func (m *OptionsRequest) String() string { return proto.CompactTextString(m) }
func (*OptionsRequest) ProtoMessage()    {}
func (*OptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9566e6e864d2854, []int{0}
}

func (m *OptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionsRequest.Unmarshal(m, b)
}
func (m *OptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionsRequest.Marshal(b, m, deterministic)
}
func (m *OptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionsRequest.Merge(m, src)
}
func (m *OptionsRequest) XXX_Size() int {
	return xxx_messageInfo_OptionsRequest.Size(m)
}
func (m *OptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OptionsRequest proto.InternalMessageInfo

func (m *OptionsRequest) GetSegment() string {
	if m != nil {
		return m.Segment
	}
	return ""
}

func (m *OptionsRequest) GetMsisdn() string {
	if m != nil {
		return m.Msisdn
	}
	return ""
}

func (m *OptionsRequest) GetBillType() string {
	if m != nil {
		return m.BillType
	}
	return ""
}

func (m *OptionsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *OptionsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type OptionsResponse struct {
	Vaulted                 bool     `protobuf:"varint,1,opt,name=vaulted,proto3" json:"vaulted,omitempty"`
	AvailablePaymentOptions []string `protobuf:"bytes,2,rep,name=availablePaymentOptions,proto3" json:"availablePaymentOptions,omitempty"`
	Cards                   []*Card  `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	TopupOptions            []int32  `protobuf:"varint,4,rep,packed,name=topupOptions,proto3" json:"topupOptions,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *OptionsResponse) Reset()         { *m = OptionsResponse{} }
func (m *OptionsResponse) String() string { return proto.CompactTextString(m) }
func (*OptionsResponse) ProtoMessage()    {}
func (*OptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9566e6e864d2854, []int{1}
}

func (m *OptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionsResponse.Unmarshal(m, b)
}
func (m *OptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionsResponse.Marshal(b, m, deterministic)
}
func (m *OptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionsResponse.Merge(m, src)
}
func (m *OptionsResponse) XXX_Size() int {
	return xxx_messageInfo_OptionsResponse.Size(m)
}
func (m *OptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OptionsResponse proto.InternalMessageInfo

func (m *OptionsResponse) GetVaulted() bool {
	if m != nil {
		return m.Vaulted
	}
	return false
}

func (m *OptionsResponse) GetAvailablePaymentOptions() []string {
	if m != nil {
		return m.AvailablePaymentOptions
	}
	return nil
}

func (m *OptionsResponse) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *OptionsResponse) GetTopupOptions() []int32 {
	if m != nil {
		return m.TopupOptions
	}
	return nil
}

type Card struct {
	PanLast4             string   `protobuf:"bytes,1,opt,name=panLast4,proto3" json:"panLast4,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ExtToken             string   `protobuf:"bytes,3,opt,name=extToken,proto3" json:"extToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9566e6e864d2854, []int{2}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetPanLast4() string {
	if m != nil {
		return m.PanLast4
	}
	return ""
}

func (m *Card) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Card) GetExtToken() string {
	if m != nil {
		return m.ExtToken
	}
	return ""
}

type DeleteCardRequest struct {
	PanLast4             string   `protobuf:"bytes,1,opt,name=panLast4,proto3" json:"panLast4,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCardRequest) Reset()         { *m = DeleteCardRequest{} }
func (m *DeleteCardRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCardRequest) ProtoMessage()    {}
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9566e6e864d2854, []int{3}
}

func (m *DeleteCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCardRequest.Unmarshal(m, b)
}
func (m *DeleteCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCardRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCardRequest.Merge(m, src)
}
func (m *DeleteCardRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCardRequest.Size(m)
}
func (m *DeleteCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCardRequest proto.InternalMessageInfo

func (m *DeleteCardRequest) GetPanLast4() string {
	if m != nil {
		return m.PanLast4
	}
	return ""
}

func (m *DeleteCardRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type DeleteCardResponse struct {
	DeletionResult       string   `protobuf:"bytes,1,opt,name=deletionResult,proto3" json:"deletionResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCardResponse) Reset()         { *m = DeleteCardResponse{} }
func (m *DeleteCardResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCardResponse) ProtoMessage()    {}
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9566e6e864d2854, []int{4}
}

func (m *DeleteCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCardResponse.Unmarshal(m, b)
}
func (m *DeleteCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCardResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCardResponse.Merge(m, src)
}
func (m *DeleteCardResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCardResponse.Size(m)
}
func (m *DeleteCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCardResponse proto.InternalMessageInfo

func (m *DeleteCardResponse) GetDeletionResult() string {
	if m != nil {
		return m.DeletionResult
	}
	return ""
}

func init() {
	proto.RegisterType((*OptionsRequest)(nil), "payments.OptionsRequest")
	proto.RegisterType((*OptionsResponse)(nil), "payments.OptionsResponse")
	proto.RegisterType((*Card)(nil), "payments.Card")
	proto.RegisterType((*DeleteCardRequest)(nil), "payments.DeleteCardRequest")
	proto.RegisterType((*DeleteCardResponse)(nil), "payments.DeleteCardResponse")
}

func init() { proto.RegisterFile("payments.proto", fileDescriptor_a9566e6e864d2854) }

var fileDescriptor_a9566e6e864d2854 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xdb, 0x30,
	0x14, 0xc7, 0x97, 0x26, 0x69, 0xd3, 0xb7, 0x29, 0xd3, 0xac, 0x69, 0xf3, 0xba, 0x1d, 0xa2, 0x68,
	0x9a, 0x72, 0xea, 0xa1, 0xe3, 0xc0, 0x81, 0x03, 0x52, 0xb9, 0x20, 0x21, 0x81, 0xac, 0x7e, 0x01,
	0x97, 0x3c, 0xa1, 0x08, 0xc7, 0x31, 0xb1, 0x53, 0xd1, 0x6f, 0xc1, 0x8d, 0x8f, 0xc1, 0x57, 0x44,
	0x4e, 0xe2, 0x94, 0x42, 0x39, 0x70, 0xf3, 0xff, 0xfd, 0xec, 0xe7, 0xff, 0xfb, 0xdb, 0x10, 0x2b,
	0xbe, 0x2d, 0x51, 0x1a, 0x3d, 0x57, 0x75, 0x65, 0x2a, 0x12, 0x39, 0x9d, 0x3e, 0x78, 0x10, 0x5f,
	0x2a, 0x53, 0x54, 0x52, 0x33, 0xbc, 0x6b, 0x50, 0x1b, 0x42, 0x61, 0xa2, 0xf1, 0xc6, 0x62, 0xea,
	0x25, 0x5e, 0x36, 0x65, 0x4e, 0x92, 0x1f, 0x30, 0x2e, 0x75, 0xa1, 0x73, 0x49, 0x47, 0x2d, 0xe8,
	0x15, 0x99, 0x41, 0xb4, 0x2e, 0x84, 0x58, 0x6d, 0x15, 0x52, 0xbf, 0x25, 0x83, 0xb6, 0xac, 0xd1,
	0x58, 0x4b, 0x5e, 0x22, 0x0d, 0x3a, 0xe6, 0x34, 0xf9, 0x0e, 0x21, 0x96, 0xbc, 0x10, 0x34, 0x6c,
	0x41, 0x27, 0xd2, 0x27, 0x0f, 0xbe, 0x0e, 0x96, 0xb4, 0xaa, 0xa4, 0x46, 0xeb, 0x69, 0xc3, 0x1b,
	0x61, 0x30, 0x6f, 0x3d, 0x45, 0xcc, 0x49, 0x72, 0x0c, 0x3f, 0xf9, 0x86, 0x17, 0x82, 0xaf, 0x05,
	0x5e, 0x75, 0x53, 0xf5, 0x87, 0xe9, 0x28, 0xf1, 0xb3, 0x29, 0x7b, 0x0f, 0x93, 0xbf, 0x10, 0x5e,
	0xf3, 0x3a, 0xd7, 0xd4, 0x4f, 0xfc, 0xec, 0xf3, 0x22, 0x9e, 0x0f, 0x21, 0x2d, 0x79, 0x9d, 0xb3,
	0x0e, 0x92, 0x14, 0xbe, 0x98, 0x4a, 0x35, 0xca, 0x35, 0x0d, 0x12, 0x3f, 0x0b, 0xd9, 0x5e, 0x2d,
	0x65, 0x10, 0xd8, 0x23, 0x76, 0x56, 0xc5, 0xe5, 0x05, 0xd7, 0xe6, 0xa8, 0x8f, 0x6e, 0xd0, 0x84,
	0x40, 0x60, 0x6c, 0x3e, 0x5d, 0x72, 0xed, 0xda, 0xee, 0xc7, 0x7b, 0xb3, 0xaa, 0x6e, 0x51, 0xba,
	0xdc, 0x9c, 0x4e, 0x97, 0xf0, 0xed, 0x0c, 0x05, 0x1a, 0x6c, 0xcd, 0xf4, 0x4f, 0xf3, 0xc1, 0x0b,
	0xd2, 0x13, 0x20, 0x2f, 0x9b, 0xf4, 0x61, 0xfe, 0x83, 0x38, 0xb7, 0xd5, 0xa2, 0x92, 0x0c, 0x75,
	0x23, 0xdc, 0x3b, 0xbf, 0xaa, 0x2e, 0x1e, 0x3d, 0x88, 0xfa, 0xcc, 0x34, 0x39, 0x85, 0x89, 0x0b,
	0x8e, 0xee, 0x92, 0xda, 0xff, 0x3a, 0xb3, 0x5f, 0x07, 0x48, 0x77, 0x69, 0xfa, 0x89, 0x9c, 0x03,
	0xec, 0xcc, 0x90, 0xdf, 0xbb, 0xad, 0x6f, 0xe6, 0x9c, 0xfd, 0x39, 0x0c, 0x5d, 0xab, 0xf5, 0xb8,
	0xfd, 0xc6, 0xff, 0x9f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xe2, 0xc3, 0x85, 0xd8, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentsClient is the client API for Payments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentsClient interface {
	Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*OptionsResponse, error)
	DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*DeleteCardResponse, error)
}

type paymentsClient struct {
	cc *grpc.ClientConn
}

func NewPaymentsClient(cc *grpc.ClientConn) PaymentsClient {
	return &paymentsClient{cc}
}

func (c *paymentsClient) Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*OptionsResponse, error) {
	out := new(OptionsResponse)
	err := c.cc.Invoke(ctx, "/payments.Payments/Options", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*DeleteCardResponse, error) {
	out := new(DeleteCardResponse)
	err := c.cc.Invoke(ctx, "/payments.Payments/DeleteCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServer is the server API for Payments service.
type PaymentsServer interface {
	Options(context.Context, *OptionsRequest) (*OptionsResponse, error)
	DeleteCard(context.Context, *DeleteCardRequest) (*DeleteCardResponse, error)
}

// UnimplementedPaymentsServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentsServer struct {
}

func (*UnimplementedPaymentsServer) Options(ctx context.Context, req *OptionsRequest) (*OptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Options not implemented")
}
func (*UnimplementedPaymentsServer) DeleteCard(ctx context.Context, req *DeleteCardRequest) (*DeleteCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCard not implemented")
}

func RegisterPaymentsServer(s *grpc.Server, srv PaymentsServer) {
	s.RegisterService(&_Payments_serviceDesc, srv)
}

func _Payments_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.Payments/Options",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Options(ctx, req.(*OptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.Payments/DeleteCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).DeleteCard(ctx, req.(*DeleteCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payments_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payments.Payments",
	HandlerType: (*PaymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Options",
			Handler:    _Payments_Options_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _Payments_DeleteCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments.proto",
}
